---
title: "Análise do Safira por camada"
author: "Panosso AR & Oliveira CF"
date: "09/03/2022"
output: html_document
---

## Carregando pacotes
```{r,message=FALSE,error=FALSE,warning=FALSE}
library(nlme)
library(tidyverse)
library(ExpDes.pt)
source("../R/minhas-funcoes.R")
theme_set(theme_bw())
```

## Análise para Safira
```{r}
raiz_soca <- readr::read_rds("../data/raiz_cana_soca") %>% 
  select(tratamento, repeticao, local, prof, volume_cm3_dm3, area_cm2_dm3,
         comprimento_total_cm_dm3,comprimento_05_cm_dm3,comprimento_2_cm_dm3,
         comprimento_m2_cm_dm3)

raiz_planta <- readr::read_rds("../data/raiz_cana_planta") %>% 
  select(tratamento, repeticao, local, prof, volume_cm3_dm3, area_cm2_dm3,
         comprimento_total_cm_dm3,comprimento_05_cm_dm3,comprimento_2_cm_dm3,
         comprimento_m2_cm_dm3)
```

## Anova para Safira Cana Planta
```{r}
variaveis <- names(raiz_planta[5:length(raiz_planta)])
camada <- unique(raiz_planta$prof)
for(i in seq_along(variaveis)){
  for(j in seq_along(camada)){
    print("======================================")
    print(paste0("Análise para: ",variaveis[i], "; Camada: ",camada[j]))
    print("======================================")
    y <- raiz_planta %>% dplyr::filter(prof == camada[j]) %>% select(variaveis[i]) %>% pull()
    preparo <- raiz_planta %>%  dplyr::filter(prof == camada[j]) %>% 
      select(tratamento) %>% pull() %>% as_factor()
    local <- raiz_planta %>%  dplyr::filter(prof == camada[j]) %>% 
      select(local) %>% pull() %>% as_factor()
    fat2.dic(preparo,local,y,
             fac.names = c("Preparo","Local"))
    
    cat("\n")
    print("===============")
    print("    Médias     ")
    print("===============")
    print(tapply(y,data.frame(local,preparo),mean,na.rm=TRUE))
  }
}
```

## Anova para Safira Cana Soca
```{r}
variaveis <- names(raiz_soca[5:length(raiz_soca)])
camada <- unique(raiz_soca$prof)
for(i in seq_along(variaveis)){
  for(j in seq_along(camada)){
    print("======================================")
    print(paste0("Análise para: ",variaveis[i], "; Camada: ",camada[j]))
    print("======================================")
    y <- raiz_soca %>% dplyr::filter(prof == camada[j]) %>% select(variaveis[i]) %>% pull()
    preparo <- raiz_soca %>% dplyr::filter(prof == camada[j]) %>%
      select(tratamento) %>% pull() %>% as_factor()
    local <- raiz_soca %>% dplyr::filter(prof == camada[j]) %>%
      select(local) %>% pull() %>% as_factor()
    fat2.dic(preparo,local,y,
             fac.names = c("Preparo","Local"))
    
    cat("\n")
    print("===============")
    print("    Médias     ")
    print("===============")
    print(tapply(y,data.frame(local,preparo),mean,na.rm=TRUE))
  }
}
```

## Visualização de Dados Cana Planta

```{r}
raiz_planta %>% 
  mutate(
    tratamento = case_when(
      tratamento == "T1" ~ "PC",
      tratamento == "T2" ~ "Adubo Verde",
      tratamento == "T4" ~ "Rip Strip",
      tratamento == "T6" ~ "PD",
    ),
    prof = case_when(
      prof == "P1" ~ "0,00-0,20",
      prof == "P2" ~ "0,20-0,40",
      prof == "P3" ~ "0,40-0,60",
    )
  ) %>% 
  group_by(tratamento, prof) %>% 
  summarise(Y = mean(volume_cm3_dm3,na.rm=TRUE),
            epm = meu_erro_padrao(volume_cm3_dm3)) %>% 
  ggplot(aes(x=tratamento, y=Y, fill=prof)) +
  geom_col(position = "dodge",color="black") +
  geom_errorbar(aes(ymin=Y-epm, ymax=Y+epm), width=.2,                 position=position_dodge(.9))+
  labs(x="Preparo",
       y=expression(paste("Volume radicular (",cm^{3}," ", dm^{-3},")"),sep=""),
       fill = "Profundidade (m)")+
  theme(legend.position = "bottom") +
  scale_fill_manual(values=c('#999999','#E69F00',"#228B22"))
```

```{r}
raiz_planta %>% 
  mutate(
    tratamento = case_when(
      tratamento == "T1" ~ "PC",
      tratamento == "T2" ~ "Adubo Verde",
      tratamento == "T4" ~ "Rip Strip",
      tratamento == "T6" ~ "PD",
    ),
    prof = case_when(
      prof == "P1" ~ "0,00-0,20",
      prof == "P2" ~ "0,20-0,40",
      prof == "P3" ~ "0,40-0,60",
    )
  ) %>% 
  group_by(tratamento, prof) %>% 
  summarise(Y = mean(area_cm2_dm3,na.rm=TRUE),
            epm = meu_erro_padrao(area_cm2_dm3)) %>% 
  ggplot(aes(x=tratamento, y=Y, fill=prof)) +
  geom_col(position = "dodge",color="black") +
  geom_errorbar(aes(ymin=Y-epm, ymax=Y+epm), width=.2,                 position=position_dodge(.9))+
  labs(x="Preparo",
       y=expression(paste("Área radicular (",cm^{2}," ", dm^{-3},")"),sep=""),
       fill = "Profundidade (m)")+
  theme(legend.position = "bottom") +
  scale_fill_manual(values=c('#999999','#E69F00',"#228B22"))
```

```{r}
raiz_planta %>% 
  mutate(
    tratamento = case_when(
      tratamento == "T1" ~ "PC",
      tratamento == "T2" ~ "Adubo Verde",
      tratamento == "T4" ~ "Rip Strip",
      tratamento == "T6" ~ "PD",
    ),
    prof = case_when(
      prof == "P1" ~ "0,00-0,20",
      prof == "P2" ~ "0,20-0,40",
      prof == "P3" ~ "0,40-0,60",
    )
  ) %>% 
  group_by(tratamento, prof) %>% 
  summarise(Y = mean(comprimento_total_cm_dm3,na.rm=TRUE),
            epm = meu_erro_padrao(comprimento_total_cm_dm3)) %>% 
  ggplot(aes(x=tratamento, y=Y, fill=prof)) +
  geom_col(position = "dodge",color="black") +
  geom_errorbar(aes(ymin=Y-epm, ymax=Y+epm), width=.2,                 position=position_dodge(.9))+
  labs(x="Preparo",
       y=expression(paste("Comprimento Radicular Total (",cm," ", dm^{-3},")"),sep=""),
       fill = "Profundidade (m)")+
  theme(legend.position = "bottom") +
  scale_fill_manual(values=c('#999999','#E69F00',"#228B22"))
```


```{r}
raiz_planta %>% 
  mutate(
    tratamento = case_when(
      tratamento == "T1" ~ "PC",
      tratamento == "T2" ~ "Adubo Verde",
      tratamento == "T4" ~ "Rip Strip",
      tratamento == "T6" ~ "PD",
    ),
    prof = case_when(
      prof == "P1" ~ "0,00-0,20",
      prof == "P2" ~ "0,20-0,40",
      prof == "P3" ~ "0,40-0,60",
    )
  ) %>% 
  group_by(tratamento, prof) %>% 
  summarise(Y = mean(comprimento_05_cm_dm3,na.rm=TRUE),
            epm = meu_erro_padrao(comprimento_05_cm_dm3)) %>% 
  ggplot(aes(x=tratamento, y=Y, fill=prof)) +
  geom_col(position = "dodge",color="black") +
  geom_errorbar(aes(ymin=Y-epm, ymax=Y+epm), width=.2,                 position=position_dodge(.9))+
  labs(x="Preparo",
       y=expression(paste(CR[0.5]," (",cm," ", dm^{-3},")"),sep=""),
       fill = "Profundidade (m)")+
  theme(legend.position = "bottom") +
  scale_fill_manual(values=c('#999999','#E69F00',"#228B22"))
```

```{r}
raiz_planta %>% 
  mutate(
    tratamento = case_when(
      tratamento == "T1" ~ "PC",
      tratamento == "T2" ~ "Adubo Verde",
      tratamento == "T4" ~ "Rip Strip",
      tratamento == "T6" ~ "PD",
    ),
    prof = case_when(
      prof == "P1" ~ "0,00-0,20",
      prof == "P2" ~ "0,20-0,40",
      prof == "P3" ~ "0,40-0,60",
    )
  ) %>% 
  group_by(tratamento, prof) %>% 
  summarise(Y = mean(comprimento_2_cm_dm3,na.rm=TRUE),
            epm = meu_erro_padrao(comprimento_2_cm_dm3)) %>% 
  ggplot(aes(x=tratamento, y=Y, fill=prof)) +
  geom_col(position = "dodge",color="black") +
  geom_errorbar(aes(ymin=Y-epm, ymax=Y+epm), width=.2,                 position=position_dodge(.9))+
  labs(x="Preparo",
       y=expression(paste(CR[0.5-2.0]," (",cm," ", dm^{-3},")"),sep=""),
       fill = "Profundidade (m)")+
  theme(legend.position = "bottom") +
  scale_fill_manual(values=c('#999999','#E69F00',"#228B22"))
```

```{r}
raiz_planta %>% 
  mutate(
    tratamento = case_when(
      tratamento == "T1" ~ "PC",
      tratamento == "T2" ~ "Adubo Verde",
      tratamento == "T4" ~ "Rip Strip",
      tratamento == "T6" ~ "PD",
    ),
    prof = case_when(
      prof == "P1" ~ "0,00-0,20",
      prof == "P2" ~ "0,20-0,40",
      prof == "P3" ~ "0,40-0,60",
    )
  ) %>% 
  group_by(tratamento, prof) %>% 
  summarise(Y = mean(comprimento_m2_cm_dm3,na.rm=TRUE),
            epm = meu_erro_padrao(comprimento_m2_cm_dm3)) %>% 
  ggplot(aes(x=tratamento, y=Y, fill=prof)) +
  geom_col(position = "dodge",color="black") +
  geom_errorbar(aes(ymin=Y-epm, ymax=Y+epm), width=.2,                 position=position_dodge(.9))+
  labs(x="Preparo",
       y=expression(paste(CR[2.0]," (",cm," ", dm^{-3},")"),sep=""),
       fill = "Profundidade (m)")+
  theme(legend.position = "bottom") +
  scale_fill_manual(values=c('#999999','#E69F00',"#228B22"))
```


## Visualização de Dados Cana Soca

```{r}
raiz_soca %>% 
  mutate(
    tratamento = case_when(
      tratamento == "1" ~ "PC",
      tratamento == "2" ~ "Adubo Verde",
      tratamento == "4" ~ "Rip Strip",
      tratamento == "6" ~ "PD",
    ),
    prof = case_when(
      prof == "P1" ~ "0,00-0,20",
      prof == "P2" ~ "0,20-0,40",
      prof == "P3" ~ "0,40-0,60",
    )
  ) %>% 
  group_by(tratamento, prof) %>% 
  summarise(Y = mean(volume_cm3_dm3,na.rm=TRUE),
            epm = meu_erro_padrao(volume_cm3_dm3)) %>% 
  ggplot(aes(x=tratamento, y=Y, fill=prof)) +
  geom_col(position = "dodge",color="black") +
  geom_errorbar(aes(ymin=Y-epm, ymax=Y+epm), width=.2,                 position=position_dodge(.9))+
  labs(x="Preparo",
       y=expression(paste("Volume radicular (",cm^{3}," ", dm^{-3},")"),sep=""),
       fill = "Profundidade (m)")+
  theme(legend.position = "bottom") +
  scale_fill_manual(values=c('#999999','#E69F00',"#228B22"))
```

```{r}
raiz_soca %>% 
  mutate(
    tratamento = case_when(
      tratamento == "1" ~ "PC",
      tratamento == "2" ~ "Adubo Verde",
      tratamento == "4" ~ "Rip Strip",
      tratamento == "6" ~ "PD",
    ),
    prof = case_when(
      prof == "P1" ~ "0,00-0,20",
      prof == "P2" ~ "0,20-0,40",
      prof == "P3" ~ "0,40-0,60",
    )
  ) %>% 
  group_by(tratamento, prof) %>% 
  summarise(Y = mean(area_cm2_dm3,na.rm=TRUE),
            epm = meu_erro_padrao(area_cm2_dm3)) %>% 
  ggplot(aes(x=tratamento, y=Y, fill=prof)) +
  geom_col(position = "dodge",color="black") +
  geom_errorbar(aes(ymin=Y-epm, ymax=Y+epm), width=.2,                 position=position_dodge(.9))+
  labs(x="Preparo",
       y=expression(paste("Área radicular (",cm^{2}," ", dm^{-3},")"),sep=""),
       fill = "Profundidade (m)")+
  theme(legend.position = "bottom") +
  scale_fill_manual(values=c('#999999','#E69F00',"#228B22"))
```

```{r}
raiz_soca %>% 
  mutate(
    tratamento = case_when(
      tratamento == "1" ~ "PC",
      tratamento == "2" ~ "Adubo Verde",
      tratamento == "4" ~ "Rip Strip",
      tratamento == "6" ~ "PD",
    ),
    prof = case_when(
      prof == "P1" ~ "0,00-0,20",
      prof == "P2" ~ "0,20-0,40",
      prof == "P3" ~ "0,40-0,60",
    )
  ) %>% 
  group_by(tratamento, prof) %>% 
  summarise(Y = mean(comprimento_total_cm_dm3,na.rm=TRUE),
            epm = meu_erro_padrao(comprimento_total_cm_dm3)) %>% 
  ggplot(aes(x=tratamento, y=Y, fill=prof)) +
  geom_col(position = "dodge",color="black") +
  geom_errorbar(aes(ymin=Y-epm, ymax=Y+epm), width=.2,                 position=position_dodge(.9))+
  labs(x="Preparo",
       y=expression(paste("Comprimento Radicular Total (",cm," ", dm^{-3},")"),sep=""),
       fill = "Profundidade (m)")+
  theme(legend.position = "bottom") +
  scale_fill_manual(values=c('#999999','#E69F00',"#228B22"))
```


```{r}
raiz_soca %>% 
  mutate(
    tratamento = case_when(
      tratamento == "1" ~ "PC",
      tratamento == "2" ~ "Adubo Verde",
      tratamento == "4" ~ "Rip Strip",
      tratamento == "6" ~ "PD",
    ),
    prof = case_when(
      prof == "P1" ~ "0,00-0,20",
      prof == "P2" ~ "0,20-0,40",
      prof == "P3" ~ "0,40-0,60",
    )
  ) %>% 
  group_by(tratamento, prof) %>% 
  summarise(Y = mean(comprimento_05_cm_dm3,na.rm=TRUE),
            epm = meu_erro_padrao(comprimento_05_cm_dm3)) %>% 
  ggplot(aes(x=tratamento, y=Y, fill=prof)) +
  geom_col(position = "dodge",color="black") +
  geom_errorbar(aes(ymin=Y-epm, ymax=Y+epm), width=.2,                 position=position_dodge(.9))+
  labs(x="Preparo",
       y=expression(paste(CR[0.5]," (",cm," ", dm^{-3},")"),sep=""),
       fill = "Profundidade (m)")+
  theme(legend.position = "bottom") +
  scale_fill_manual(values=c('#999999','#E69F00',"#228B22"))
```

```{r}
raiz_soca %>% 
  mutate(
    tratamento = case_when(
      tratamento == "1" ~ "PC",
      tratamento == "2" ~ "Adubo Verde",
      tratamento == "4" ~ "Rip Strip",
      tratamento == "6" ~ "PD",
    ),
    prof = case_when(
      prof == "P1" ~ "0,00-0,20",
      prof == "P2" ~ "0,20-0,40",
      prof == "P3" ~ "0,40-0,60",
    )
  ) %>% 
  group_by(tratamento, prof) %>% 
  summarise(Y = mean(comprimento_2_cm_dm3,na.rm=TRUE),
            epm = meu_erro_padrao(comprimento_2_cm_dm3)) %>% 
  ggplot(aes(x=tratamento, y=Y, fill=prof)) +
  geom_col(position = "dodge",color="black") +
  geom_errorbar(aes(ymin=Y-epm, ymax=Y+epm), width=.2,                 position=position_dodge(.9))+
  labs(x="Preparo",
       y=expression(paste(CR[0.5-2.0]," (",cm," ", dm^{-3},")"),sep=""),
       fill = "Profundidade (m)")+
  theme(legend.position = "bottom") +
  scale_fill_manual(values=c('#999999','#E69F00',"#228B22"))
```

```{r}
raiz_soca %>% 
  mutate(
    tratamento = case_when(
      tratamento == "1" ~ "PC",
      tratamento == "2" ~ "Adubo Verde",
      tratamento == "4" ~ "Rip Strip",
      tratamento == "6" ~ "PD",
    ),
    prof = case_when(
      prof == "P1" ~ "0,00-0,20",
      prof == "P2" ~ "0,20-0,40",
      prof == "P3" ~ "0,40-0,60",
    )
  ) %>% 
  group_by(tratamento, prof) %>% 
  summarise(Y = mean(comprimento_m2_cm_dm3,na.rm=TRUE),
            epm = meu_erro_padrao(comprimento_m2_cm_dm3)) %>% 
  ggplot(aes(x=tratamento, y=Y, fill=prof)) +
  geom_col(position = "dodge",color="black") +
  geom_errorbar(aes(ymin=Y-epm, ymax=Y+epm), width=.2,                 position=position_dodge(.9))+
  labs(x="Preparo",
       y=expression(paste(CR[2.0]," (",cm," ", dm^{-3},")"),sep=""),
       fill = "Profundidade (m)")+
  theme(legend.position = "bottom") +
  scale_fill_manual(values=c('#999999','#E69F00',"#228B22"))
```
