---
title: "Análise Física e Química por camada"
author: "Panosso AR & Oliveira CF"
date: "03/05/2022"
output: html_document
---

## Carregando pacotes
```{r,message=FALSE,error=FALSE,warning=FALSE}
library(nlme)
library(tidyverse)
library(ExpDes.pt)
source("../R/minhas-funcoes.R")
theme_set(theme_bw())
```

## Análise para Física e Química
```{r}
fisica_quimica <- readr::read_rds("../data/fisica_quimica")
```

## Análise de Variância
```{r}
variaveis <- names(fisica_quimica[7:length(fisica_quimica)])
camada <- unique(fisica_quimica$prof)
for(j in 1:2){
  for(i in seq_along(variaveis)){
    for(k in seq_along(camada)){
      print("======================================")
      print(paste0("Análise para: ",variaveis[i],"; Ciclo: ",j," Camada: ", camada[k]))
      print("======================================")
      y <- fisica_quimica %>% filter(ciclo==j & prof == camada[k]) %>%  select(variaveis[i]) %>% pull()
      preparo <- fisica_quimica %>% 
        dplyr::filter(ciclo==j & prof == camada[k]) %>% select(preparo) %>% pull() %>% as_factor()
      local <- fisica_quimica %>% 
        dplyr::filter(ciclo==j & prof == camada[k]) %>% select(local) %>% pull() %>% as_factor()
      bloco <- fisica_quimica %>% 
        dplyr::filter(ciclo==j & prof == camada[k]) %>% select(repeticao) %>% pull() %>% as_factor()
      prof <- fisica_quimica %>%  
        dplyr::filter(ciclo==j & prof == camada[k]) %>% select(prof) %>% pull() %>% as_factor()
      parc <- interaction(bloco, preparo, drop=TRUE)
      subp <- interaction(bloco, preparo, local, drop=TRUE)
      mod <- lme(y~bloco+preparo*local, random=~1|parc/subp,
                 method="ML")
      print(anova(mod))
      print("----------------------------------")
      fat2.dbc(preparo,local,bloco,y,
               fac.names = c("Preparo","Local"))
      
      cat("\n") 
      print("===============")
      print("    Médias     ")
      print("===============")
      print(tapply(y,data.frame(local,preparo),mean))
    }
  }
}
```




